version: '3.9'

services:
  db:
    container_name: db
    image: joshevan/solomon-postgres
    build:
      context: backend-api
      dockerfile: postgres.Dockerfile
    environment:
      - POSTGRES_USER=solomon
      - POSTGRES_PASSWORD=proverb
      - POSTGRES_DB=solomon-db
    volumes:
      - solomon-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  elasticsearch:
    image: elasticsearch:8.8.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - network.host=0.0.0.0

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    # volumes:
    #   - /path/to/local/data:/root/redis
    #   - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=proverb
      - REDIS_PORT=6379

  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160"
      - "4161"
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150"
      - "4151"
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd  
    ports:
      - "4171:4171"

  app:
    container_name: app
    image: joshevan/solomon-backend
    build:
      context: backend-api
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "9099:9099"
    links:
      - db
    restart: always

  cerebro:
    platform: linux/amd64
    image: lmenezes/cerebro:latest
    ports:
      - "9000:9000"
    depends_on:
     - elasticsearch


  # frontend:
  #   container_name: frontend
  #   image: joshevan/solomon-frontend
  #   build:
  #     context: frontend
  #     dockerfile: frontend.Dockerfile
  #   depends_on:
  #     - app
  #   ports:
  #     - "5001:5001"

volumes:
  solomon-postgres:
    external: true
