config:
  db:
    driver: "pgx"
    conn_str: "user=solomon password=proverb host=db port=5432 dbname=solomon-db sslmode=disable pool_max_conns=9"
  search_engine: 
    address: "http://elasticsearch:9200"
  cache:
    address: "redis:6379"
    password: "proverb"
  event_bus:
    publish_address: "nsqd:4150"

  consumer:
    listen_address: "nsqlookupd:4160"
    listen:
      event_solomon_upsert_product_es:
        topic: "event_solomon_upsert_product_es"
        channel: "solomon"
