config:
  db:
    driver: "pgx"
    conn_str: "user=solomon password=proverb host=db port=5432 dbname=solomon-db sslmode=disable pool_max_conns=9"
  search_engine: 
    address: "http://elasticsearch:9200"
  cache:
    address: "redis:6379"
    password: "proverb"
